### ISSUE TITLE
Is it possible to use docker-py 

### ISSUE THREAD

**Issue by js1019** [popperized/normalmodes-workflows#15]
Is it possible to use [docker-py](https://github.com/docker/docker-py) instead of docker? I download popper via "pip install popper --user" and can also install docker in a similar way. But I am not sure how can I use it. Please let me know if it is a good way. Thanks!

**Comment by ivotron** [comment]
Sorry for the confusion @js1019. The `docker-py` python package provides only the python bindings for the Docker container runtime, which needs to be installed separately. Instructions are available on the [official website](https://docs.docker.com/install/). Alternatively, you can install Singularity 3.2 (see [here](https://sylabs.io/guides/3.2/user-guide/installation.html) for instructions). Please let me know if we can help in any way

**Comment by js1019** [comment]
> Sorry for the confusion @js1019. The `docker-py` python package provides only the python bindings for the Docker container runtime, which needs to be installed separately. Instructions are available on the [official website](https://docs.docker.com/install/). Alternatively, you can install Singularity 3.2 (see [here](https://sylabs.io/guides/3.2/user-guide/installation.html) for instructions). Please let me know if we can help in any way

Got it. Thanks!
